/**
 * SafeX Centralized Emergency & Incident Constants
 */

const EMERGENCY_TYPES = ['MEDICAL', 'POLICE', 'ACCIDENT', 'LOST', 'HARASSMENT', 'OTHER'];

const EMERGENCY_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

const EMERGENCY_STATUSES = [
  'NEW',
  'ACKNOWLEDGED',
  'RESPONDER_ASSIGNED',
  'IN_PROGRESS',
  'RESOLVED',
  'CANCELLED'
];

// Strictly enforced status workflow transitions
const VALID_EMERGENCY_TRANSITIONS = {
  NEW: ['ACKNOWLEDGED', 'CANCELLED'],
  ACKNOWLEDGED: ['RESPONDER_ASSIGNED', 'CANCELLED'],
  RESPONDER_ASSIGNED: ['IN_PROGRESS', 'CANCELLED'],
  IN_PROGRESS: ['RESOLVED'],
  RESOLVED: [],
  CANCELLED: []
};

// Active statuses that prevent duplicate SOS creation
const ACTIVE_EMERGENCY_STATUSES = ['NEW', 'ACKNOWLEDGED', 'RESPONDER_ASSIGNED', 'IN_PROGRESS'];

const INCIDENT_TYPES = [
  'THEFT',
  'HARASSMENT',
  'ACCIDENT',
  'MISSING_PERSON',
  'FRAUD',
  'SAFETY_CONCERN',
  'OTHER'
];

const INCIDENT_STATUSES = [
  'REPORTED',
  'UNDER_REVIEW',
  'VERIFIED',
  'RESOLVED',
  'REJECTED'
];

const EMERGENCY_SERVICE_TYPES = ['POLICE', 'HOSPITAL', 'HOTEL'];

module.exports = {
  EMERGENCY_TYPES,
  EMERGENCY_SEVERITIES,
  EMERGENCY_STATUSES,
  VALID_EMERGENCY_TRANSITIONS,
  ACTIVE_EMERGENCY_STATUSES,
  INCIDENT_TYPES,
  INCIDENT_STATUSES,
  EMERGENCY_SERVICE_TYPES
};
